services:
  gpu-test:
    image: ubuntu
    container_name: gpu-test-container
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              capabilities: ["gpu"]
              device_ids:
                - nvidia.com/gpu=all
    command: ["sh", "-c", "nvidia-smi -L && sleep infinity"]
